package com.stockmanagement.stockmn.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
@Data
public class LoginRequestDTO {
    private String email;  // Private field to store email address
    private String password;
    // Getters and setters were automatically generated by Lombok's @Data annotation
}
