package com.stockmanagement.stockmn.entity;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity  // Specifies that this class is an entity mapped to a database table
@NoArgsConstructor
@AllArgsConstructor
@Data
public class Product {
    @Id  // Specifies the primary key of the entity
    private String product_id;  // Unique identifier for the product
    private String product_name;  // Name of the product
    private int selling_percentage;
    private int sale_item;
    private int sale_percentage;
    private int buying_price;
    private int stock_clearing_item;
    private int stock_clearing_price;
    private int quantity;
    private String vendor_name;
    private String material_type;
    private String material_name;
    private String vendor_address;
    private String vendor_type;
    private int selling_price;

    // Getters and setters were automatically generated by Lombok's @Data annotation
}